import streamlit as st
from PyPDF2 import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from gpt4all import GPT4All


def chunk_pdf_langchain(document):
    if document is None:
        return []

    pdf = PdfReader(document)
    full_text = ""

    for page in pdf.pages:
        if page.extract_text():
            full_text += page.extract_text() + "\n"

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        separators=["\n\n", "\n", ". ", " ", ""],
        length_function=len,
    )

    return text_splitter.split_text(full_text)


def embed_and_store_chunks(chunks):
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    embeddings = model.encode(chunks, show_progress_bar=True)
    embeddings = np.array(embeddings).astype("float32")
    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)
    return embeddings, index, chunks


def embed_question(question):
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    question_embedding = model.encode([question], show_progress_bar=False)
    return np.array(question_embedding).astype("float32")


def retrieve_relevant_chunks(question_embedding, index, chunks, top_k=3):
    distances, indices = index.search(question_embedding, top_k)
    relevant_chunks = [chunks[i] for i in indices[0]]
    return relevant_chunks


# LOAD LOCAL GPT4ALL MODEL (Professor's approach)
@st.cache_resource
def load_llm():
    model_dir = r"w:\7_Semester\Machine Learning\labs\Lab11\models"
    model_name = "q4_0-orca-mini-3b.gguf"
    return GPT4All(
        model_name=model_name,
        model_path=model_dir,
        allow_download=False
    )


def generate_answer(relevant_chunks, question):
    context = "\n\n".join(relevant_chunks)
    
    prompt = f"""You are an AI assistant that helps users find information from a document.
Use the following context to answer the question at the end. If you don't know the answer, just say you don't know. Do not make up an answer.

Context:
{context}

Question: {question}
Answer:"""

    try:
        llm = load_llm()
        answer = llm.generate(prompt, max_tokens=512, temp=0.1)
        return answer
    except Exception as e:
        return f"⚠️ Model Error: {str(e)}\n\nHere are the relevant sections:\n\n{context}"




st.title("Retrieval-Augmented Generation")

st.write("""
        This application demonstrates Retrieval-Augmented Generation (RAG) using Streamlit.""")

st.write("""
        Upload a PDF document, ask questions about its content, and receive answers generated by a language model augmented with information retrieved from the document.
        """)

document = st.file_uploader("Upload your PDF document", type=["pdf"])

if document is not None:
    st.success("Document uploaded successfully!")

    # Process the document
    with st.spinner("Processing document..."):
        chunks = chunk_pdf_langchain(document)
    st.write(f"Document split into {len(chunks)} chunks")

    # Embed and index
    with st.spinner("Embedding and indexing document..."):
        embeddings, index, chunks = embed_and_store_chunks(chunks)
    st.write("Document indexed!")

    question = st.text_input("Ask a question about the document:")

    if question:
        st.write("You asked:", question)
        
        with st.spinner("Generating answer..."):
            # Get question embedding
            question_embedding = embed_question(question)

            # Retrieve relevant chunks
            relevant_chunks = retrieve_relevant_chunks(question_embedding, index, chunks)

            # Generate answer
            answer = generate_answer(relevant_chunks, question)

        st.write("Answer:", answer)